# Generated by Django 4.2.4 on 2023-09-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.creditcard'),
        ),
    ]
