# Generated by Django 4.2.4 on 2023-09-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_credit_card_account_is_credit_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_credit_card',
        ),
    ]
