# Generated by Django 4.2.4 on 2023-09-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_is_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
