# Generated by Django 4.2.4 on 2023-09-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_creditcard_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
