# Generated by Django 4.2.4 on 2023-09-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_options_currency_numeric_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='numeric_code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
