# Generated by Django 4.2.4 on 2023-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_exchangeratecurrent_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeratecurrent',
            old_name='sold_currency',
            new_name='currency1',
        ),
        migrations.RenameField(
            model_name='exchangeratecurrent',
            old_name='bought_currency',
            new_name='currency2',
        ),
        migrations.RenameField(
            model_name='exchangeratecurrent',
            old_name='rate',
            new_name='rate_buy',
        ),
        migrations.AddField(
            model_name='exchangeratecurrent',
            name='rate_sell',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=16),
            preserve_default=False,
        ),
    ]
