# Generated by Django 4.2.4 on 2023-09-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_numeric_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='numeric_code',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
