# Generated by Django 4.2.4 on 2023-09-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_rename_sold_currency_exchangeratecurrent_currency1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeratecurrent',
            options={'verbose_name': 'current exchange rates', 'verbose_name_plural': 'current exchange rates'},
        ),
        migrations.AlterModelOptions(
            name='exchangeratehistory',
            options={'verbose_name': 'history of exchange rates', 'verbose_name_plural': 'history of exchange rates'},
        ),
    ]
