# Generated by Django 4.2.4 on 2023-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_alter_currency_numeric_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
