# Generated by Django 4.2.4 on 2023-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_operation_type_delete_operationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='amount'),
        ),
    ]
