# Generated by Django 4.2.4 on 2023-09-03 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operation_exchange_rate_alter_operation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='op_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 8, 2, 50, 641088, tzinfo=datetime.timezone.utc), verbose_name='operation date'),
        ),
    ]
